name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11', '3.12']
        platform: [ubuntu-latest, macos-latest, windows-latest]
      runs-on: ${{ matrix.platform }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Install Python ${{ matrix.python }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python }}
        - name: Install dependencies
          run: python -m pip install
        - name: Run Tests
          run:  pytest -vv
        - name: Lint
          run: ruff check
